app/main/default/objects/Margin_Rule__c/Margin_Rule__c.object-meta.xml
<CustomObject>
    <label>Margin Rule</label>
    <nameField>
        <displayFormat>MR-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Margin Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

app/main/default/objects/Margin_Rule__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly_Charges__c</fullName>
                <label>Monthly Charges</label>
            </value>
            <value>
                <fullName>Install_Charges__c</fullName>
                <label>Install Charges</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

app/main/default/objects/Margin_Rule__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Addition</fullName>
            </value>
            <value>
                <fullName>Factor</fullName>
            </value>
            <value>
                <fullName>Set</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

app/main/default/objects/Product2/fields/Install_Charges__c.field-meta.xml
<CustomField>
    <fullName>Install_Charges__c</fullName>
    <label>Install Charges</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

app/main/default/objects/Product2/fields/Monthly_Charges__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Charges__c</fullName>
    <label>Monthly Charges</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

app/main/default/objects/Purchase_Product__c/Purchase_Product__c.object-meta.xml
<CustomObject>
    <label>Purchase Product</label>
    <nameField>
        <displayFormat>PP-{000000}</displayFormat>
        <label>Product Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

app/main/default/objects/Purchase_Product__c/fields/Install_Charges__c.field-meta.xml
<CustomField>
    <fullName>Install_Charges__c</fullName>
    <label>Install Charges</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

app/main/default/objects/Purchase_Product__c/fields/Monthly_Charges__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Charges__c</fullName>
    <label>Monthly Charges</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

app/main/default/classes/MarginServiceTest.cls
@IsTest
public class MarginServiceTest {

    @IsTest
    static void applayMarginTest() {

        List<Margin_Rule__c> marginRules = new List<Margin_Rule__c>{
            new Margin_Rule__c(Field__c = 'Install_Charges__c', Type__c = 'Addition', Value__c = 12),
            new Margin_Rule__c(Field__c = 'Install_Charges__c', Type__c = 'Factor', Value__c = 8),
            new Margin_Rule__c(Field__c = 'Monthly_Charges__c', Type__c = 'Set', Value__c = 120)
        };
        insert marginRules;

        List<Purchase_Product__c> purchaseProducts = new List<Purchase_Product__c>();
        for (Integer i = 1; i <= 10; i++) {
            Purchase_Product__c pp = new Purchase_Product__c(Install_Charges__c = 50 * i, Monthly_Charges__c = 78 * 2 * i);
            purchaseProducts.add(pp);
        }
        insert purchaseProducts;

        Test.startTest();
        MarginService.applayMargin(purchaseProducts);
        Test.stopTest();

        purchaseProducts = [SELECT Monthly_Charges__c, Install_Charges__c  FROM Purchase_Product__c];
        List<Product2> products = [SELECT Monthly_Charges__c, Install_Charges__c FROM Product2];

        System.assertEquals(120, purchaseProducts[0].Monthly_Charges__c);
        System.assertEquals(purchaseProducts[0].Install_Charges__c, products[0].Install_Charges__c);
        System.assertEquals(496, products[0].Install_Charges__c);
    }

}