app/main/default/objects/Margin_Rule__c/Margin_Rule__c.object-meta.xml
<CustomObject>
    <label>Margin Rule</label>
    <nameField>
        <displayFormat>MR-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Margin Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

app/main/default/objects/Margin_Rule__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly_Charges__c</fullName>
                <label>Monthly Charges</label>
            </value>
            <value>
                <fullName>Install_Charges__c</fullName>
                <label>Install Charges</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

app/main/default/objects/Margin_Rule__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Addition</fullName>
            </value>
            <value>
                <fullName>Factor</fullName>
            </value>
            <value>
                <fullName>Set</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

app/main/default/objects/Purchase_Product__c/Purchase_Product__c.object-meta.xml
<CustomObject>
    <label>Purchase Product</label>
    <nameField>
        <displayFormat>PP-{000000}</displayFormat>
        <label>Product Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

app/main/default/classes/MarginService.cls
public with sharing class MarginService{

    public static void applayMargin(List<Purchase_Product__c> purchaseProducts) {

        List<Margin_Rule__c> marginRules = [SELECT Field__c, Type__c, Value__c FROM Margin_Rule__c LIMIT 10000];

        for (Purchase_Product__c pp : purchaseProducts) {
            for (Margin_Rule__c marginRule : marginRules) {

                if (marginRule.Type__c == 'Addition') {
                    pp.put(
                        marginRule.Field__c,
                        (Decimal)pp.get(marginRule.Field__c) + marginRule.Value__c
                    );
                }

                if (marginRule.Type__c == 'Factor') {
                    pp.put(
                        marginRule.Field__c,
                        (Decimal)pp.get(marginRule.Field__c) * marginRule.Value__c
                    );
                }

                if (marginRule.Type__c == 'Set') {
                    pp.put(marginRule.Field__c, marginRule.Value__c);
                }
            }
        }

        update purchaseProducts;
    }
}